version: '2'

services:

#-------------------------------------------
# NGINX
#-------------------------------------------
  nginx:
    build:
      context: ./nginx
    volumes:
      - ${DATA_SAVE}/nginx/default:/etc/nginx/site-available/default  
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_VERSION=${NGINX_VERSION}
      - NJS_VERSION=${NJS_VERSION}
    networks:
      - frontend
      - backend

#-------------------------------------------------------------------
# NODEJS
#-------------------------------------------------------------------
  node:
    build:
      context: ./node
    environment:
      - NODE_VERSION=${NODE_VERSION}
      - YARN_VERSION=${YARN_VERSION}
    networks:
      - frontend
      - backend

#-------------------------------------------------------------------
# POSTGRESQL
#-------------------------------------------------------------------
  postgres:
    build: ./postgresql
    volumes:
      - ${DATA_SAVE}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend


#-------------------------------------------
# RUBY
#-------------------------------------------
  ruby:
    build:
      context: ./ruby
    environment:
      - RUBY_MAJOR=${RUBY_MAJOR}
      - RUBY_VERSION=${RUBY_VERSION}
      - RUBY_DOWNLOAD_SHA256=${RUBY_DOWNLOAD_SHA256}
      - RUBYGEMS_VERSION=${RUBYGEMS_VERSION}
      - BUNDLER_VERSION=${BUNDLER_VERSION}
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  nginx:
    driver: "local"
  node:
    driver: "local"
  postgres:
    driver: "local"
  ruby:
    driver: "local"