version: '2'

services:

#-------------------------------------------------------------------
# NGINX 
#-------------------------------------------------------------------
  nginx:
    build:
      context: .
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_VERSION=${NGINX_VERSION}
      - NJS_VERSION=${NJS_VERSION}
    networks:
      - frontend
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  nginx:
    driver: "local"