version: '2'

services:

#-------------------------------------------------------------------
# NODEJS
#-------------------------------------------------------------------
  node:
    build:
      context: .
    environment:
      - NODE_VERSION=${NODE_VERSION}
      - YARN_VERSION=${YARN_VERSION}
    networks:
      - frontend
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  node:
    driver: "local"